a.out: menu.o Add.o Print.o Delete.o Find.o Reverse.o Edit.o Save.o Sync.o
	cc menu.o Add.o Print.o Delete.o Find.o Reverse.o Edit.o Save.o Sync.o
menu.o:menu.c
	cc -c menu.c
Add.o:Add.c
	cc -c Add.c
Print.o:Print.c
	cc -c Print.c
Delete.o:Delete.c
	cc -c Delete.c
Find.o:Find.c
	cc -c Find.c
Reverse.o:Reverse.c
	cc -c Reverse.c
Edit.o:Edit.c
	cc -c Edit.c
Save.o:Save.c
	cc -c Save.c
Sync.o:Sync.c
	cc -c Sync.c